
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: jvm-spring-demo
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: jvm-spring-demo
    spec:
      containers:
      - image: <TAG>
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 9080
